[remote]
host = "cronos" # use the name of a frontal (crfront1) for nobatch test
plugins = ["nobatch", "slurm"] # plugins to test
protocols = ["ssh", "paramiko"] # protocols to test
work_dir = "/scratch/users/I35256/workingdir/pybatch"
wckey = "P120K:SALOME"
is_posix = true # use false for a remote Windows server.
gss_auth = true # use kerberos authentication

[local]
# plugin "slurm" to test on the frontal of a cluster.
# plugins = ["nobatch", "slurm"]
plugins = ["nobatch"]
# wckey = "P120K:SALOME"
