[remote]
host = "gaia"
plugins = ["nobatch", "slurm"]
# plugins = ["slurm"]
protocols = ["ssh", "paramiko"]
work_dir = "/scratch/I35256/workingdir/pybatch"
wckey = "P120K:SALOME"
is_posix = true # use false for a remote Windows server.
gss_auth = true # use kerberos authentication

[local]
# plugin "slurm" to test on the frontal of a cluster.
plugins = ["local", "slurm"]
wckey = "P120K:SALOME"
